title: MyFirstGridSite
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8050483
  brandStrength: 0.4150634377729148
  lightness: 0.6670464
  brandColors:
    - '#F6F402'
    - '#1F1F1F'
    - '#DCD900'
    - '#666666'
    - '#ADADAD'
  rhythmicContrast: 0.9006445
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: isaac_
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8845327
layout_spectrum: 1
